from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT
from pathlib import Path
from datetime import datetime
from PIL import Image
import hashlib
import math
import numpy as np


class PDFReporter:
    """
    Enterprise Forensic PDF Report Generator for StegHunter
    """

    def __init__(self):
        self.styles = getSampleStyleSheet()

        self.title_style = ParagraphStyle(
            'ForensicTitle',
            parent=self.styles['Title'],
            fontName='Helvetica-Bold',
            fontSize=24,
            textColor=colors.HexColor("#0B5394"),
            alignment=TA_LEFT,
            spaceAfter=8
        )

        self.subtitle_style = ParagraphStyle(
            'ForensicSubTitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=colors.grey,
            spaceAfter=12
        )

        self.heading_style = ParagraphStyle(
            'SectionHeading',
            parent=self.styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=colors.HexColor("#0B5394"),
            spaceBefore=8,
            spaceAfter=8
        )

        self.normal_style = ParagraphStyle(
            'BodyNormal',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13
        )

        self.small_style = ParagraphStyle(
            'SmallBody',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=11
        )

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------
    def _draw_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        footer_text = f"Generated by StegHunter - Hybrid Steganography Detection Framework | Page {doc.page}"
        canvas.drawString(20 * mm, 10 * mm, footer_text)
        canvas.restoreState()

    # ---------------------------------------------------------
    # SAFE FLOAT
    # ---------------------------------------------------------
    def _safe_float(self, value, default=0.0):
        try:
            if value is None:
                return default

            if isinstance(value, np.generic):
                value = float(value)

            value = float(value)

            if math.isnan(value) or math.isinf(value):
                return default

            return value
        except Exception:
            return default

    # ---------------------------------------------------------
    # CASE ID
    # ---------------------------------------------------------
    def _generate_case_id(self):
        return "SH-" + datetime.now().strftime("%Y%m%d-%H%M%S")

    # ---------------------------------------------------------
    # VERDICT
    # ---------------------------------------------------------
    def _derive_forensic_verdict(self, score: float) -> str:
        score = self._safe_float(score)

        if score >= 85:
            return "STEGANOGRAPHY DETECTED (CRITICAL)"
        elif score >= 70:
            return "HIGHLY SUSPICIOUS"
        elif score >= 50:
            return "MODERATELY SUSPICIOUS"
        elif score >= 25:
            return "LOW SUSPICION"
        else:
            return "NO STRONG EVIDENCE DETECTED"

    def _risk_label(self, score: float) -> str:
        score = self._safe_float(score)

        if score >= 80:
            return "CRITICAL"
        elif score >= 60:
            return "HIGH"
        elif score >= 40:
            return "MODERATE"
        elif score >= 20:
            return "LOW"
        return "MINIMAL"

    # ---------------------------------------------------------
    # SCORE METER
    # ---------------------------------------------------------
    def _score_meter(self, score: float) -> Table:
        score = self._safe_float(score)
        filled = int(score // 5)
        meter = "█" * filled + "░" * (20 - filled)

        data = [[f"{meter}   {score:.2f} / 100"]]

        t = Table(data, colWidths=[170 * mm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EAF3FB")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#0B5394")),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor("#0B5394")),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 11),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        return t

    # ---------------------------------------------------------
    # FILE INTELLIGENCE
    # ---------------------------------------------------------
    def _collect_file_intelligence(self, image_path: str):
        with open(image_path, "rb") as f:
            raw = f.read()

        md5 = hashlib.md5(raw).hexdigest()
        sha256 = hashlib.sha256(raw).hexdigest()
        size = f"{round(Path(image_path).stat().st_size / 1024, 2)} KB"

        with Image.open(image_path) as img:
            dimensions = f"{img.width} x {img.height}"
            histogram = img.convert("L").histogram()

        total = sum(histogram)
        entropy = 0.0

        if total > 0:
            for h in histogram:
                if h != 0:
                    p = h / total
                    entropy -= p * math.log2(p)

        return {
            "md5": md5,
            "sha256": sha256,
            "size": size,
            "dimensions": dimensions,
            "entropy": f"{entropy:.3f}"
        }

    # ---------------------------------------------------------
    # FORENSIC REASONING TEXT
    # ---------------------------------------------------------
    def _extract_reasoning_text(self, analysis_results: dict) -> str:
        raw = analysis_results.get(
            "forensic_reasoning",
            analysis_results.get(
                "reasoning",
                "Hybrid detector fusion identified multiple low-level statistical anomalies across the submitted image. "
                "Detector evidence was aggregated using weighted forensic consensus methodology."
            )
        )
        return self._safe_text(raw)


    # ---------------------------------------------------------
    # PAYLOAD REGION TEXT
    # ---------------------------------------------------------
    def _extract_payload_region_text(self, analysis_results: dict) -> str:
        payload = analysis_results.get("payload_location", {})

        if isinstance(payload, dict) and payload:
            return self._safe_text(payload)

        return "No sharply isolated payload concentration zone was conclusively identified."
    
        # ---------------------------------------------------------
    # MAIN REPORT GENERATOR
    # ---------------------------------------------------------
    def generate_report(self, analysis_results: dict, image_path: str, output_path: str, heatmap_path: str = None):
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=20,
            leftMargin=20,
            topMargin=20,
            bottomMargin=25
        )

        elements = []

        final_score = self._safe_float(
            analysis_results.get("final_suspicion_score", analysis_results.get("overall_score", 0))
        )

        confidence = self._safe_float(
            analysis_results.get("confidence_score", analysis_results.get("ml_probability", 0) * 100)
        )

        verdict = self._derive_forensic_verdict(final_score)
        case_id = self._generate_case_id()

        # =====================================================
        # PAGE 1 — COVER + EXECUTIVE SUMMARY
        # =====================================================
        elements.append(Paragraph("STEGHUNTER DIGITAL FORENSIC REPORT", self.title_style))
        elements.append(Paragraph("Hybrid Steganography Detection Framework", self.subtitle_style))
        elements.append(Paragraph(f"Case ID: {case_id}", self.small_style))
        elements.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M:%S')}", self.small_style))
        elements.append(Spacer(1, 0.18 * inch))

        verdict_table = Table([
            ["FINAL VERDICT", verdict],
            ["SUSPICION SCORE", f"{final_score:.2f} / 100"],
            ["CONFIDENCE", f"{confidence:.2f}%"]
        ], colWidths=[55 * mm, 110 * mm])

        verdict_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EAF3FB")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#0B5394")),
            ('GRID', (0,0), (-1,-1), 0.7, colors.HexColor("#0B5394")),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ]))

        elements.append(verdict_table)
        elements.append(Spacer(1, 0.15 * inch))
        elements.append(self._score_meter(final_score))
        elements.append(Spacer(1, 0.25 * inch))

        # ORIGINAL IMAGE PREVIEW
        try:
            with Image.open(image_path) as img:
                img_width = 5.8 * inch
                img_height = (img.height / img.width) * img_width

                if img_height > 3.5 * inch:
                    img_height = 3.5 * inch
                    img_width = (img.width / img.height) * img_height

            elements.append(Paragraph("Analyzed Evidence Image", self.heading_style))
            elements.append(RLImage(str(Path(image_path)), width=img_width, height=img_height))
            elements.append(Spacer(1, 0.2 * inch))
        except Exception:
            elements.append(Paragraph("(Evidence image preview unavailable)", self.normal_style))

        # FILE INTELLIGENCE
        intel = self._collect_file_intelligence(image_path)

        elements.append(Paragraph("File Intelligence Summary", self.heading_style))

        intel_table = Table([
            ["Filename", Path(image_path).name],
            ["File Size", intel["size"]],
            ["Dimensions", intel["dimensions"]],
            ["Entropy", intel["entropy"]],
            ["MD5", intel["md5"]],
            ["SHA256", intel["sha256"][:42] + "..."]
        ], colWidths=[40 * mm, 125 * mm])

        intel_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
            ('BOX', (0,0), (-1,-1), 0.8, colors.grey),
            ('GRID', (0,0), (-1,-1), 0.4, colors.lightgrey),
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
        ]))

        elements.append(intel_table)
        elements.append(PageBreak())
        
            # =====================================================
        # PAGE 2 — DETECTOR DASHBOARD
        # =====================================================
        elements.append(Paragraph("Detector Intelligence Dashboard", self.title_style))
        elements.append(Spacer(1, 0.15 * inch))

        detector_rows = [["Detector", "Score", "Severity", "Evidence Summary"]]

        methods = analysis_results.get("methods", {})

        for key, value in methods.items():
            if not isinstance(value, dict):
                continue

            raw_score = (
                value.get("suspicion_score")
                if value.get("suspicion_score") is not None else
                value.get("lsb_suspicion_score")
                if value.get("lsb_suspicion_score") is not None else
                value.get("basic_suspicion_score")
            )

            score = self._safe_float(raw_score, 0.0)
            risk = self._risk_label(score)

            summary = []
            for k, v in value.items():
                if "score" not in k.lower() and "map" not in k.lower() and "matrix" not in k.lower():
                    txt = f"{k}:{self._safe_text(v)}"
                    summary.append(txt)

            summary_text = " | ".join(summary[:2])
            if len(summary_text) > 70:
                summary_text = summary_text[:67] + "..."

            detector_rows.append([
                key.replace("_", " ").title(),
                f"{score:.2f}",
                risk,
                summary_text if summary_text else "-"
            ])

        detector_table = Table(detector_rows, colWidths=[38*mm, 20*mm, 25*mm, 95*mm])

        detector_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0B5394")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 7),
            ('GRID', (0,0), (-1,-1), 0.4, colors.grey),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.whitesmoke, colors.HexColor("#F7FBFF")]),
            ('ALIGN', (1,1), (2,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))

        elements.append(detector_table)
        elements.append(Spacer(1, 0.2 * inch))

        # KEY FINDINGS BOX
        findings = [
            f"• {len(methods)} forensic detector modules contributed to hybrid evidence fusion.",
            f"• Highest anomaly concentration observed at suspicion score {final_score:.2f}.",
            "• Statistical, structural, compression, and payload localization indicators were jointly evaluated.",
            "• Final forensic conclusion reflects weighted consensus rather than single-detector dependence."
        ]

        findings_table = Table([[Paragraph("<br/>".join(findings), self.normal_style)]], colWidths=[170*mm])
        findings_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EEF6FF")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#0B5394")),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))

        elements.append(Paragraph("Key Forensic Findings", self.heading_style))
        elements.append(findings_table)
        elements.append(PageBreak())

        # =====================================================
        # PAGE 3 — ANALYST REASONING
        # =====================================================
        elements.append(Paragraph("Analyst Interpretation & Hybrid Forensic Reasoning", self.title_style))
        elements.append(Spacer(1, 0.15 * inch))

        reasoning_text = self._extract_reasoning_text(analysis_results)
        payload_text = self._extract_payload_region_text(analysis_results)

        elements.append(Paragraph("Forensic Reasoning Narrative", self.heading_style))
        elements.append(Paragraph(reasoning_text, self.normal_style))
        elements.append(Spacer(1, 0.18 * inch))

        elements.append(Paragraph("Payload Localization Interpretation", self.heading_style))
        elements.append(Paragraph(payload_text, self.normal_style))
        elements.append(Spacer(1, 0.2 * inch))
        
            # HEATMAP EVIDENCE
        if heatmap_path and Path(heatmap_path).exists():
            try:
                with Image.open(heatmap_path) as hm:
                    hm_width = 5.8 * inch
                    hm_height = (hm.height / hm.width) * hm_width

                    if hm_height > 4.5 * inch:
                        hm_height = 4.5 * inch
                        hm_width = (hm.width / hm.height) * hm_height

                elements.append(Paragraph("Suspicious Region Heatmap Evidence", self.heading_style))
                elements.append(RLImage(str(Path(heatmap_path)), width=hm_width, height=hm_height))
                elements.append(Spacer(1, 0.2 * inch))
            except Exception:
                elements.append(Paragraph("(Heatmap evidence unavailable)", self.normal_style))
        else:
            elements.append(Paragraph("No external heatmap evidence attached.", self.normal_style))
            elements.append(Spacer(1, 0.2 * inch))

        # PAYLOAD FINDING BOX
        payload_box = Table([[
            Paragraph(
                "Hybrid payload localization suggests that hidden-content probability is not uniformly distributed. "
                "Consensus anomalies arise from parity irregularities, structural detector imbalance, and compression "
                "inconsistency zones that jointly indicate statistically suspicious neighborhoods.",
                self.normal_style
            )
        ]], colWidths=[170*mm])

        payload_box.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F5FAFF")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#0B5394")),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))

        elements.append(payload_box)
        elements.append(PageBreak())

        # =====================================================
        # PAGE 4 — FINAL CONCLUSION
        # =====================================================
        elements.append(Paragraph("Final Forensic Conclusion Certificate", self.title_style))
        elements.append(Spacer(1, 0.2 * inch))

        conclusion_text = (
            f"The submitted digital image was subjected to a hybrid steganographic forensic examination using "
            f"multiple statistical, structural, compression-domain, metadata, machine-assisted, and localization-based "
            f"detector modules. Weighted detector consensus produced an overall suspicion score of {final_score:.2f}/100, "
            f"leading to the final forensic classification: <b>{verdict}</b>."
        )

        elements.append(Paragraph(conclusion_text, self.normal_style))
        elements.append(Spacer(1, 0.18 * inch))

        methodology = (
            "Methodology employed includes LSB irregularity inspection, chi-square deviation testing, RS/SPA parity "
            "analysis, DCT coefficient examination, JPEG ghost artifact screening, clone/noise anomaly mapping, "
            "Error Level Analysis, metadata consistency validation, and hybrid payload localization."
        )

        elements.append(Paragraph("Methodology Applied", self.heading_style))
        elements.append(Paragraph(methodology, self.normal_style))
        elements.append(Spacer(1, 0.18 * inch))

        disclaimer = (
            "This report is automatically generated by StegHunter and is intended as a digital forensic decision-support "
            "artifact. Final legal or evidentiary interpretation should incorporate analyst review and contextual chain-of-custody considerations."
        )

        disc_table = Table([[Paragraph(disclaimer, self.small_style)]], colWidths=[170*mm])
        disc_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
            ('BOX', (0,0), (-1,-1), 0.7, colors.grey),
        ]))

        elements.append(Paragraph("Analyst Note", self.heading_style))
        elements.append(disc_table)
        elements.append(PageBreak())
        
        # =====================================================
        # PAGE 5 — RECOMMENDATIONS & ACTION ITEMS
        # =====================================================
        elements.append(Paragraph("Recommendations & Next Steps", self.title_style))
        elements.append(Spacer(1, 0.15 * inch))
        
        # Risk level box
        risk_label = self._risk_label(final_score)
        risk_colors = {
            "CRITICAL": "#d32f2f",
            "HIGH": "#f57c00",
            "MODERATE": "#fbc02d",
            "LOW": "#388e3c",
            "MINIMAL": "#1976d2"
        }
        risk_color = risk_colors.get(risk_label, "#1976d2")
        
        risk_box = Table([[
            Paragraph(f"<b>RISK LEVEL: {risk_label}</b>", self.heading_style)
        ]], colWidths=[170*mm])
        risk_box.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(risk_color)),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.white),
            ('BOX', (0,0), (-1,-1), 2, colors.HexColor(risk_color)),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        elements.append(risk_box)
        elements.append(Spacer(1, 0.15 * inch))
        
        # Action items based on verdict
        recommendations = self._generate_recommendations(verdict, final_score)
        for rec in recommendations:
            elements.append(Paragraph(rec, self.normal_style))
        
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("Detailed Technical Findings", self.heading_style))
        elements.append(Spacer(1, 0.1 * inch))
        
        # Detailed findings table
        findings = self._generate_detailed_findings(analysis_results)
        if findings:
            for finding in findings:
                elements.append(Paragraph(finding, self.normal_style))
                elements.append(Spacer(1, 0.08 * inch))
        else:
            elements.append(Paragraph("No detailed findings available.", self.normal_style))
        
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("Summary Statistics", self.heading_style))
        
        # Statistics table
        stats_data = [
            ["Total Detection Methods", str(len(analysis_results.get("methods", {})))],
            ["Average Anomaly Score", f"{final_score:.2f}/100"],
            ["Confidence Level", f"{confidence:.2f}%"],
            ["Analysis Timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        ]
        
        stats_table = Table(stats_data, colWidths=[80*mm, 85*mm])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0B5394")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#F0F0F0")),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(stats_table)

        # BUILD PDF
        doc.build(elements, onFirstPage=self._draw_footer, onLaterPages=self._draw_footer)

        return output_path
    
    def _safe_text(self, value, default="N/A"):
        try:
            if value is None:
                return default

            if isinstance(value, dict):
                parts = []
                for k, v in value.items():
                    parts.append(f"{k}: {v}")
                return " | ".join(parts)

            if isinstance(value, (list, tuple, set)):
                return " | ".join(str(x) for x in value)

            text = str(value).strip()

            if not text:
                return default

            return text
        except Exception:
            return default